SET IDENTITY_INSERT [dbo].[compte] ON 

INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (1, NULL, NULL, NULL, NULL, N'autorisation@environnement.gov.ma', NULL, N'autorisation', N'$2a$10$ttgK0gl8snxCUefu8P9speFxhcJnjqWGXonsgjWbhGYPRNDqsKDku', N'0656197687', 1, NULL, NULL, N'2', 2, N'oui')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4288, NULL, NULL, NULL, NULL, N'drissi@environnement.gov.ma', NULL, N'DRISSI  lalla Amina ', N'$2a$10$ozkUXR27WCQCMzDU8EAF7utzTGxTeaHFODWFuRiF.9972agqGgQYe', N'0654545123', 1, 1019, NULL, N'1', 6, N'oui')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4289, NULL, NULL, NULL, NULL, N'damghi@environnement.gov.ma', NULL, N'DAMGHI  Hanane ', N'$2a$10$6E8ZHRiS1J7LmwfIlyOo3uHwXeN41FBBowixpn42Pej091pTGyHJC', N'0654545123', 1, 1028, NULL, N'1', 6, N'no')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4290, NULL, NULL, NULL, NULL, N'aharmim@environnement.gov.ma', NULL, N'Naima Aharmim', N'$2a$10$BHhQa4Ja1UGPoTkSai7Jwe/2zHd0DtUe8ydxwB0tIoBJdyf7e/VLK', N'0654545123', 1, 1028, NULL, N'1', 6, N'no')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4291, NULL, NULL, NULL, NULL, N'oubaydallah2@environnement.gov.ma', NULL, N'Oubaydallah Zakia', N'$2a$10$JGzROlX9Ih81sWCmAr1c4uQHfjoUsX.fed7L0UbWBDBBPGRy.wvsS', N'0654545123', 1, 1023, NULL, N'1', 6, N'no')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4292, NULL, NULL, NULL, NULL, N'saddik@environnement.gov.ma', NULL, N'Saddik Mohammed', N'$2a$10$FuNliwTEcE5EhVRqRUYinOBAbNzgYHi/v8OgJ5HYWtHqkdJ5kp1re', N'0654545123', 1, 1027, NULL, N'1', 6, N'no')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4293, NULL, NULL, NULL, NULL, N'chokri@environnement.gov.ma', NULL, N'ECH-CHOKRI Rachid ', N'$2a$10$bPX3xewig6suD4dLZl5BTuoWGljHEDO86N/yLINxZ6IWkMgTAT82S', N'0654545123', 1, 1027, NULL, N'1', 6, N'no')
INSERT [dbo].[compte] ([compte_id], [commission], [delete_date_time], [deleted], [depot], [email], [email_recup], [nom], [password], [tel], [profil_id], [region_id], [societes_id], [typeregion], [id_poste], [chequer]) VALUES (4294, NULL, NULL, NULL, NULL, N'elmaakoul@environnement.gov.ma', NULL, N'El maakoul Asma', N'$2a$10$pAIyKwCC1ICM4nylzT5oyOQ9XTcO91kj9tffo2XX9kDqVzIdwi5sy', N'0654545123', 1, 1026, NULL, N'1', 6, N'no')
SET IDENTITY_INSERT [dbo].[compte] OFF
GO