

update reponse set description_fr=N'<li>Tous types des déchets Dangereux et non Dangereux <a href="/CatalogueDesDechet1" target="_blank">(Voir le Catalogue Marocaine des déchets)</a></li>' where id_reponse =141
update reponse set description_fr=N'<ul class="style_square">  <li> - Loi 28-00 relative à la gestion des déchets et à leur élimination </li>      <li> - Décret n° 2-07-253 portant classification des déchets et fixant la liste des déchets dangereux </li>      <li> - Décret n° 2-17-587 du 10 décembre 2018 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets (chapitre II) </li>      <li> - Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1339 du 14/07/2020 fixant la liste des déchets non dangereux pouvant être autorisés à l’importation </li>      <li> - Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1340 du 14/07/2020 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets. </li>  </ul>' where id_reponse =142
update reponse set description_fr=N'<li>   Veuillez consulter la rubrique préparer votre démarche <a href="/Preparezvotredemarche" target="_blank">(Lien)</a>.</li>  <h5 style=font-weight: bolder">Pour les déchets dangereux :</h5>  <ul class="style_square">      <li> Document de Notification ; </li>  <li> Document de Mouvement ; </li>    <li>Garantie Financière ; </li>      <li>Copie du contrat conclu entre l’exportateur des déchets et l’importateur/l’exploitant de l’installation de la valorisation ou l’élimination des déchets dangereux ; </li>      <li>Document des analyses physico-chimiques des déchets et ou Fiche d’identification ; </li>      <li>Attestation d’acceptation des déchets de l’installation de valorisation </li>  <li>L’autorisation d’exploitation de l’installation ; </li>  <li>L’autorisation de l’installation pour la valorisation des déchets dangereux et de leur élimination ;  </li>  <li>Assurance sur la responsabilité civile de l’installation de valorisation ;</li>  <li>L’autorisation de la collecte et du transport des déchets dangereux ;  </li>  <li>Cahier des charges ;  </li>  <li>Déclaration sur l’honneur sur l’exactitude des informations présentées, signée et cachetée. </li>  </ul>  <h5 style=font-weight: bolder">Pour les déchets non dangereux :</h5>  <ul class="style_square">      <li>Document de Notification ; </li>      <li>Document du Mouvement ; </li>      <li>Garantie Financière ; </li>      <li>Copie du contrat conclu entre l’exportateur des déchets et l’importateur/ l’exploitant de l’installation de la valorisation ou l’élimination ; </li>      <li>Document des analyses physico-chimiques des déchets et ou Fiche d’identification ; </li>  <li>Cahier des charges ; </li>  <li>Autorisation d’exploitation des unités de production des déchets et de leur élimination ; </li>  <li>Assurance de la responsabilité civile de l’installation ; </li>  <li>Parcours de la charge ;  </li>  <li>Modes de valorisation des déchets et leur élimination ; </li>  <li>Causes de l’importation (destination finale des déchets importés) ; </li>  <li>Déclaration sur l’honneur de la fiabilité des informations déclarées et d’absence des substances dangereuses dans les déchets importés, signée et cachetée. </li>  </ul>' where id_reponse =143
update reponse set description_fr=N'   Veuillez consulter la rubrique préparer votre démarche <a href="/Preparezvotredemarche" target="_blank">(Lien)</a>.' where id_reponse =144
update reponse set description_fr=N'La durée de l’autorisation de l’importation des déchets de la zone franche est de 2 mois.' where id_reponse =145
update reponse set description_fr=N'Seulement les déchets non dangereux.' where id_reponse =146
update reponse set description_fr=N'<ul class="style_square">  <li>Loi 28-00 relative à la gestion des déchets et à leur élimination </li>      <li>- Décret n° 2-07-253 portant classification des déchets et fixant la liste des déchets dangereux  </li>      <li>- Décret n° 2-17-587 du 10 décembre 2018 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets (chapitre III) </li>      <li>- Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1339 du 14/07/2020 fixant la liste des déchets non dangereux pouvant être autorisés à l’importation</li>      <li>- Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1340 du 14/07/2020 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets. </li>  </ul>    ' where id_reponse =147
update reponse set description_fr=N'<li>   Veuillez consulter la rubrique préparer votre démarche <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>          <li>Demande de l''autorité nationale compétente de l''État d''exportation en cas d''importation de déchets non dangereux de l’étranger ;</li>  <ul class="style_square">      <li>Document de Notification ; </li>      <li>Document de Mouvement ;</li>      <li>Copie de la garantie financière ; </li>      <li>Copie du contrat conclu entre l’exportateur des déchets et l’importateur/ l’exploitant de l’installation de la valorisation ou l’élimination ;  </li>      <li>Analyse des déchets et/ou Fiche d’identification ; </li>  <li>Cahier des charges ; </li>  <li>Autorisation d’exploitation des unités de production des déchets et de leur élimination ; </li>  <li>Assurance de la responsabilité civile de l’installation ; </li>  <li>Liste des autorités compétentes ; </li>  <li>Devis et calcul du montant de la garantie Financière ; </li>  <li>Itinéraire d’expédition ;  </li>  <li>Procédé de valorisation ou d’élimination des déchets ; </li>  <li>Causes de l’importation (destination finale des déchets importés) ; </li>  <li>Déclaration sur l’honneur de la fiabilité des informations déclarées et d’absence des substances dangereuses dans les déchets importés, signée et cachetée.</li>  </ul>' where id_reponse =148
update reponse set description_fr=N'<li>   Veuillez consulter la rubrique préparer votre démarche <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>' where id_reponse =149
update reponse set description_fr=N'La durée de validité de l’autorisation de l’importation des déchets d’un pays étranger est d’une année.' where id_reponse =150
update reponse set description_fr=N'Les déchets dangereux selon CMD qui ne peuvent pas être traités au niveau des installations existantes au Maroc.' where id_reponse =151
update reponse set description_fr=N'<ul class="style_square">  <li>-  Loi 28-00 relative à la gestion des déchets et à leur élimination   </li>      <li>- Décret n° 2-07-253 portant classification des déchets et fixant la liste des déchets dangereux</li>      <li>- Décret n° 2-17-587 du 10 décembre 2018 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets (chapitre IV) </li>      <li>- Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1339 du 14/07/2020 fixant la liste des déchets non dangereux pouvant être autorisés à l’importation   </li>      <li>- Arrêté du Ministre de l’Energie, des Mines et de l’Environnement n° 1340 du 14/07/2020 fixant la liste des déchets non dangereux pouvant être autorisés à l’importation </li>  </lu>' where id_reponse =152
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>    <ul class="style_square">      <li>Document de Notification ; </li>      <li>Document de Mouvement ;</li>      <li> Motifs d’exportation ; </li>      <li> Copie du contrat conclu entre l’exportateur des déchets et l’importateur/l’exploitant de l’installation de la valorisation ou l’élimination des déchets dangereux, destinatrice des déchets ;   </li>      <li> Certificat d’acceptation préalable ;  </li>  <li> Caractéristique des Déchets ; </li>  <li>Description des modalités de production du déchet ;   </li>  <li>Garantie financière ; </li>  <li>Liste des transporteurs ; </li>  <li>Itinéraire d’expédition ; </li>  <li> Assurances ; </li>  <li> Assurance de la responsabilité civile du transporteur ;    </li>  <li> Assurance de la responsabilité civile de la société marocaine requérante ; </li> <li>Déclaration sur l’honneur sur l’exactitude des informations signée et cachetée.</li>  </lu>' where id_reponse =153
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>' where id_reponse =154
update reponse set description_fr=N'La durée de validité de l’autorisation de l’importation des déchets d’un pays étranger est d’une année.' where id_reponse =155
update reponse set description_fr=N'Décret n° 2-17-587 fixant les conditions et les modalités d’importation, d’exportation et de transit des déchets, chapitre VI ' where id_reponse =156
update reponse set description_fr=N'<li>   Veuillez consulter la rubrique préparer votre démarche <a href="/Preparezvotredemarche" target="_blank">(Lien)</a>.</li>    <ul class="style_square">      <li>Demande de transit (l’attestation d''acceptation des déchets par la société d’élimination) ;  </li>      <li> Accord du pays d’importation ;</li>      <li>Accord du pays d’exportation ; </li>      <li>Document de notification (Signé à la case 18, vierge à la case19 et 20) ; </li>      <li>Document de mouvement ;  </li>  <li> Contrat entre le notifiant et l’éliminateur (société de valorisation) ; </li>  <li>Fiche d’identification des déchets ; </li>  <li>Origine des déchets ; </li>  <li>Devis et calcul du montant de la garantie financière ; </li>  <li>Itinéraire (trajet et destination) ;   </li>  <li> Ports de transit ;   </li>  <li>Autorités compétentes ;  </li>  <li>Transporteurs maritimes ;    </li>  <li>Assurances des transporteurs maritimes. </li>  </lu>' where id_reponse =157
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>' where id_reponse =158
update reponse set description_fr=N'La durée de validité de l’autorisation de transit des déchets est une année' where id_reponse =159
update reponse set description_fr=N'Les déchets dangereux indiquées au niveau de catalogue Marocaine des déchets ' where id_reponse =160
update reponse set description_fr=N'<ul class="style_square">      <li>-  Loi 28-00 relative à la gestion des déchets et à leur élimination  </li>      <li>- Décret n° 2-07-253 portant classification des déchets et fixant la liste des déchets dangereux</li>      <li>-  Décret n°2-14-85 relatif à la gestion des déchets dangereux du 20 janvier 2015 (chapitre III) </li>      <li>- Arrêté n° 3184-15 du 23 septembre 2015 </li>  </ul>  ' where id_reponse =161
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>  <ul class="style_square">      <li> Copie de la carte d’identité nationale (CIN) ;  </li>      <li> Type des véhicules et des conteneurs à utiliser pour transporter les déchets dangereux ; </li>      <li>Nombres des véhicules et des conteneurs (avec illustration) ; </li>      <li>Numéro d’immatriculation et numéro de châssis de chaque véhicule ;  </li>      <li>Masse totale en charge et masse nette de chaque véhicule ;</li>  <li>Capacité des conteneurs et de véhicules exprimée en poids dans le cas des déchets solides et en volumes dans les autres cas ;</li>  <li>Matériaux des compositions des conteneurs et partie de chaque véhicule utilisée pour le transport, incluant ceux de revêtement intérieur ; </li>  <li>Adresse de l’endroit où les véhicules sont remisés (justifié par un contrat et /ou titre foncier de site) ;</li>  <li>Déclaration sur la nature des déchets dangereux que le demandeur projette de collecter et de transporter ; </li>  <li>Engagement d’exercer à titre principal les activités de collecte et de transport des déchets dangereux ;</li>  <li>Document déterminants les mesures préventives et sanitaires permettant la sécurité du personnel ;</li>  <li>Documents attestant la qualification et la formation du personnel chargé de la collecte et de transport ;</li>  <li>Copie d’attestation de souscription de la police d’assurance pour chaque véhicule ;</li>  <li>Copie de la police d’assurance couvrant la responsabilité professionnelle du collecteur-transporteur ; </li> <li>Pièce justifiant la capacité financière d’exerce de l’activité. </li>  </ul> ' where id_reponse =162
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>' where id_reponse =163
update reponse set description_fr=N'La durée de validité de l’autorisation de collecte et de transport des déchets est de 5 ans.' where id_reponse =164
update reponse set description_fr=N'Les déchets dangereux indiqués au niveau de Catalogue Marocaine des déchets ' where id_reponse =165
update reponse set description_fr=N'  <ul class="style_square">      <li>-  Loi 28-00 relative à la gestion des déchets et à leur élimination  </li>      <li>- Décret n° 2-07-253 portant classification des déchets et fixant la liste des déchets dangereux </li>      <li> -  Décret n°2-14-85 relatif à la gestion des déchets dangereux du 20 janvier 2015 (chapitre IV)   </li>      <li>- Arrêté n° 3184-15 du 23 septembre 2015  </li>  </ul>' where id_reponse =166
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>  <ul class="style_square">            <li>Les informations sur la personne pétitionnaire ;  </li>      <li>Les informations sur l’installation projetée et leur site ;  </li>      <li>La nature des activités à exercer et les types et quantités des déchets ; </li>      <li>Les documents attestant le respect des prescriptions techniques et les modes de traitement, d’élimination et de valorisation des déchets prévus à l’article 29 du décret précité (Autorisation d’exploitation des unités de production et d’élimination des déchets) ;  </li>  <li> Une note relatant les précautions prises pour garantir les conditions de sécurité et de protection de l’environnement ;  </li>  <li>Une étude d’impact sur l’environnement ;  </li>  <li>La décision d’acceptabilité environnementale ;    </li>  <li>Un plan de terrain comportant les bâtiments et les installations ;  </li> <li>Un plan de site de l’installation, avec la précision de l’affectation des différentes zones de ladite installation ; </li> <li>Une description de l’installation, de sa structure et de son fonctionnement ; </li>  <li>  Une description de procédés de traitement et d’équipement ;  </li>  </lu>  <ol>  <li>      -  Capacité de traitement et les prestations de l’installation ;   </li>  <li>     -  Type d’appareils et des machines utilisés au sein de l’installation ;  </li>  <li>     - Horaires d’exploitation nombre d’équipes de travail ;      </li>  <li>     - Qualification et formation en matière de traitement des déchets dangereux.     </li>  </ol>  <ul class="style_square">            <li> Plan d’autocontrôle de gestion de l’installation ainsi que les moyens d’exécution de ce plan ;   </li>      <li> Une copie de la garantie financière destinée aux interventions en cas d’accidents ;   </li>      <li>Une pièce justifiant que le propriétaire du terrain connait la nature des activités projetées, en cas de location ou de jouissance.   </li>  </lu>  ' where id_reponse =167
update reponse set description_fr=N'<li>Veuillez consulter la rubrique préparer votre démarche   <a href="/Preparezvotredemarche" target="_blank">(Lien)</a></li>' where id_reponse =168
update reponse set description_fr=N'La durée de validité de l’autorisation de collecte et de transport des déchets est de 5 ans.' where id_reponse =169

update reponse set description=N'<li>جميع أنواع النفايات الخطرة والغير خطرة <a href="/CatalogueDesDechet1" target="_blank">(المصنف المغربي للنفايات)</a></li>' where id_reponse =141

update reponse set description_fr=N'Télécharger l’exemplaire de cahier des charges. ' where id_reponse =170
update reponse set description_fr=N'Il n’y a pas de frais exigés par l’administration pour l’obtention des différentes autorisations, toutes les autorisations délivrées par le DE sont gratuites' where id_reponse =171
